### ISSUE TITLE
Move the Arizona Wordmark into the new CDN

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/digital.arizona.edu#19]
## Motivation
We discovered that the Arizona wordmark was still being served from the old CDN

## Proposed Resolution
The University of Arizona wordmark should be served from the digital.arizona.edu CDN but using the same path as it was referenced on the old CDN: https://cdn.uadigital.arizona.edu/logos/v1.0.0/ua_wordmark_line_logo_white_rgb.min.svg

**Comment by kevcooper** [comment]
Wordmark logos have been copied to the new CDN

**Comment by kevcooper** [comment]
https://cdn.uadigital.arizona.edu/logos/v1.0.0/ua_wordmark_line_logo_white_rgb.min.svg
https://cdn.uadigital.arizona.edu/logos/v1.0.0/ua_wordmark_line_logo_white_rgb.svg
