### ISSUE TITLE
Broken links to join Slack

### ISSUE THREAD

**Issue by pbarabe** [az-digital/digital.arizona.edu#32]
## Problem/Motivation
Several of the pages on this site link to a URL on quickstart.arizona.edu that currently results in a 404 error.

### Describe the bug
Several pages have the following HTML link (or similar variant), but visiting the target URL results in a 404 Not Found error.

```html
Join the Arizona Digital discussions on <a href="https://quickstart.arizona.edu/join-us-on-slack">Slack</a>
```

Known pages w/ broken link:
- https://github.com/az-digital/digital.arizona.edu/blob/main/docs/index.html
- https://github.com/az-digital/digital.arizona.edu/blob/main/docs/arizona-bootstrap/index.html
- https://github.com/az-digital/digital.arizona.edu/blob/main/docs/getting-started/index.html
- https://github.com/az-digital/digital.arizona.edu/blob/main/docs/how-it-works/index.html
- https://github.com/az-digital/digital.arizona.edu/blob/main/docs/ua-bootstrap/index.html

### To Reproduce

1. Go to 'https://digital.arizona.edu'
2. Click on 'Join the Arizona Digital discussions on Slack'

## Proposed resolutions
- Update instructions on how to join the discussion on Slack, or
- Re-publish original URL, or
- Remove _Join Slack_ link, or
- Something else?

**Comment by pbarabe** [comment]
I'd be happy to help/submit a PR if a preferred solution is identified.

**Comment by trackleft** [comment]
I can add a redirect on quickstart.arizona.edu to that page if that is a good interim solution.  We probably want to use trellis forms for this.

**Comment by trackleft** [comment]
![image](https://user-images.githubusercontent.com/1023167/142472327-f9144b19-d84d-4b4b-937d-544a7eb156a1.png)

**Comment by joeparsons** [comment]
@camikazegreen @danahertzberg @smayden Do we have a preferred solution for this?

**Comment by trackleft** [comment]
Thanks! @camikazegreen  added a form here: https://quickstart.arizona.edu/join-us-on-slack

@joeparsons suggested redirecting https://quickstart1.arizona.edu/join-us-on-slack to the new one.
